# Generated by Django 4.2.5 on 2023-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_creators_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creators',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
