# Generated by Django 4.2.5 on 2023-10-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_creators_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creators',
            old_name='image',
            new_name='files_image',
        ),
    ]
