# Generated by Django 4.2.5 on 2023-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futiuersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('icon', models.ImageField(upload_to='testimonials/')),
                ('icon_background', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_auter', models.CharField(max_length=250)),
                ('auther_designation', models.CharField(max_length=250)),
                ('testimonial_logo', models.ImageField(upload_to='testimonials/')),
            ],
        ),
    ]
