# Generated by Django 4.2.5 on 2023-10-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_futiuersection_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creatvedeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('icon', models.FileField(upload_to='testimonials/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='futiuersection',
            name='testimonial_logo',
            field=models.FileField(upload_to='testimonials/'),
        ),
    ]
