# Generated by Django 4.2.5 on 2023-10-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_creatvedeo_alter_futiuersection_testimonial_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('icon', models.FileField(upload_to='testimonials/')),
                ('description', models.TextField()),
                ('auther', models.CharField(max_length=250)),
                ('auther_designation', models.CharField(max_length=250)),
                ('field', models.CharField(max_length=250)),
            ],
        ),
    ]
