# Generated by Django 4.2.5 on 2023-10-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_marketting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketting',
            name='image',
            field=models.FileField(upload_to='testimonials/'),
        ),
    ]
