# Generated by Django 4.2.5 on 2023-10-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('title', models.CharField(max_length=250)),
                ('title_color', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
