# Generated by Django 4.2.5 on 2023-10-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='title_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
