# Generated by Django 4.2.5 on 2023-10-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_resources_title_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('compony', models.CharField(max_length=128)),
                ('compony_size', models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '201-500')], max_length=128)),
                ('indutry', models.CharField(choices=[('1', 'Aggriculture'), ('2', 'Banking&Finance'), ('3', 'Bussiness Services & Softweare')], max_length=128)),
                ('job_role', models.CharField(choices=[('1', 'C-Suite'), ('2', 'VP')], max_length=128)),
                ('country', models.CharField(choices=[('1', 'Bangladesh'), ('2', 'China'), ('3', 'India'), ('4', 'Japan'), ('5', 'United States')], max_length=128)),
                ('user_agreement', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_contact',
                'ordering': ['-id'],
            },
        ),
    ]
