# Generated by Django 4.2.5 on 2023-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_creators_white_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='solution',
            name='her_image',
            field=models.ImageField(default='a', upload_to='testimonials/hero_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='name',
            field=models.CharField(default='Studio', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='solution',
            table='web_product',
        ),
    ]
