# Generated by Django 4.2.5 on 2023-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_solution_options_solution_her_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='color',
            field=models.CharField(default='#ffc9b7', max_length=128),
            preserve_default=False,
        ),
    ]
