# Generated by Django 4.2.5 on 2023-10-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_solution_her_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creators',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.solution'),
            preserve_default=False,
        ),
    ]
